ca-cwds/single-db-poc

- cares-ui/package.json
- cares-ui/src/LandingPage.jsx
- cares-ui/src/index.jsx
- cares-ui/src/reporter/ReporterMain.jsx
- cares-ui/src/reporter/Search.jsx
- cares-ui/yarn.lock
- https://osi-cwds.atlassian.net/browse/REP-21
- https://osi-cwds.atlassian.net/browse/REP-18
> Rep-18 create search screen

- .github/PULL_REQUEST_TEMPLATE.md
- Jenkinsfile
- build.gradle
- cares-bre/cares-bre-interfaces/build.gradle
- cares-bre/cares-bre-rest-api/build.gradle
- cares-bre/cares-bre-rest-client/build.gradle
- cares-bre/cares-bre-services/build.gradle
- cares-bre/cares-bre-services/src/main/java/gov/ca/cwds/bre/services/rules/BreDroolsService.java
- cares-common/build.gradle
- cares-geo/cares-geo-interfaces/build.gradle
- cares-geo/cares-geo-rest-client/build.gradle
- cares/cares-interfaces/build.gradle
- cares/cares-persistence/build.gradle
- cares/cares-rest-api/build.gradle
- cares/cares-services/build.gradle
- cares/cares-services/src/main/java/gov/ca/cwds/cares/services/ClientServiceImpl.java
- cares/cares-services/src/main/java/gov/ca/cwds/cares/services/ReferralServiceImpl.java
- cares/cares-services/src/main/java/gov/ca/cwds/cares/services/SystemCodeServiceImpl.java
Add Jenkins file to run pipeline. Includes test and sonarqube.
Had to fix a few sonar issues as well.
> REP-32 Setting up Jenkins for build

- Jenkinsfile
https://osi-cwds.atlassian.net/browse/REP-32
Added a Master to jenkins build
> Tparker jenkins master

- cares/cares-functional-tests/src/main/java/gov/ca/cwds/cares/rest/FunctionalTestBase.java
- cares/cares-functional-tests/src/main/java/gov/ca/cwds/cares/rest/search/ReporterSearchTest.java
- cares/cares-functional-tests/src/main/resources/gov/ca/cwds/cares/rest/FunctionalTestBase.properties
- cares/cares-functional-tests/src/main/resources/gov/ca/cwds/cares/rest/search/ReporterSearchTest.properties
https://osi-cwds.atlassian.net/browse/REP-72
> Common functional test properties

- Jenkinsfile
https://osi-cwds.atlassian.net/browse/REP-32
Added debugging for testing master build
> REP-32 add debug to gradle build

- Jenkinsfile
https://osi-cwds.atlassian.net/browse/REP-32
removed docker push from pipeline
> REP-32 Removed docker build from pipeline

- cares/cares-interfaces/src/main/java/gov/ca/cwds/cares/interfaces/api/ReporterService.java
- cares/cares-interfaces/src/main/java/gov/ca/cwds/cares/interfaces/model/people/Reporter.java
- cares/cares-interfaces/src/test/java/gov/ca/cwds/cares/interfaces/model/people/ReporterTest.java
- cares/cares-rest-api/src/main/java/gov/ca/cwds/cares/rest/controller/ReporterController.java
- cares/cares-rest-api/src/test/java/gov/ca/cwds/cares/rest/controller/ReporterControllerTest.java
- cares/cares-services/src/main/java/gov/ca/cwds/cares/services/ReporterServiceImpl.java
Stub reporter rest API has been added
https://osi-cwds.atlassian.net/browse/REP-44
> REP-44 Add stub reporter rest endpoint

- cares/cares-rest-api/src/main/java/gov/ca/cwds/cares/rest/controller/CicsMockRestController.java
Reporter mock POST endpoint
Reporter mock POST endpoint has been added
https://osi-cwds.atlassian.net/browse/REP-46
> REP-46 Add Reporter mock POST endpoint

- cares-bre/cares-bre-rest-api/src/main/java/gov/ca/cwds/bre/rest/controller/BreRestController.java
Cross origin support for BRE rest
https://osi-cwds.atlassian.net/browse/REP-49
> Cross origin support for BRE rest

- cares-ui/src/reporter/Search.jsx
- cares-ui/src/reporter/models/baseModel.js
- cares-ui/src/reporter/models/searchModel.js
- cares-ui/src/reporter/models/searchResultsModel.js
- cares-ui/src/reporter/reducers/index.js
fixing some issues with the UI and error handling
[REP-3](https://osi-cwds.atlassian.net/browse/REP-3)
[REP-80](https://osi-cwds.atlassian.net/browse/REP-80)
> REP-3 fix some error handling issues

- cares/cares-services/src/main/java/gov/ca/cwds/cares/services/ReporterServiceImpl.java
> REP-52 Fix stub service

- cares-bre/cares-bre-interfaces/src/test/java/gov/ca/cwds/bre/interfaces/exception/BreExceptionTest.java
- cares-bre/cares-bre-interfaces/src/test/java/gov/ca/cwds/bre/interfaces/model/BreRequestDataTest.java
- cares-bre/cares-bre-interfaces/src/test/java/gov/ca/cwds/bre/interfaces/model/BreRequestTest.java
- cares-bre/cares-bre-interfaces/src/test/java/gov/ca/cwds/bre/interfaces/model/BreResponseDataTest.java
- cares-bre/cares-bre-interfaces/src/test/java/gov/ca/cwds/bre/interfaces/model/BreResponseTest.java
- cares-bre/cares-bre-interfaces/src/test/java/gov/ca/cwds/bre/interfaces/model/BusinessRuleSetDefinitionTest.java
- cares-bre/cares-bre-interfaces/src/test/java/gov/ca/cwds/bre/interfaces/model/BusinessRuleSetDocumentationTest.java
- cares-bre/cares-bre-interfaces/src/test/java/gov/ca/cwds/bre/interfaces/model/RuleDefinitionTest.java
- cares-bre/cares-bre-services/build.gradle
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-R-00725.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-R-00846.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-R-00849.drl
- cares-cics/cares-cics-interfaces/src/test/resources/gov/ca/cwds/cics/model/ReporterDataBuilder.java
Add unit test for classes in cares-bre-interface 
```
gov.ca.cwds.bre.interfaces.model 
gov.ca.cwds.bre.interfaces.exception
```
Added a ReporterDataBuilder class for developing test of the Reporter business rules in the future.
Updated a couple of Reporter business rules drl files.
Corrected some syntax in Reporter business rules drl files.
> unit test for BRE interfaces/model

- cares-cics/cares-cics-interfaces/src/main/java/gov/ca/cwds/cics/model/CicsReporterRequest.java
- cares-cics/cares-cics-rest-client/src/main/java/gov/ca/cwds/cics/restclient/CicsReporterRestApiClient.java
- cares-cics/cares-cics-rest-client/src/test/java/gov/ca/cwds/cics/restclient/CicsReporterRestApiClientTest.java
- cares/cares-services/src/main/java/gov/ca/cwds/cares/services/ReporterServiceImpl.java
- cares/cares-services/src/test/java/gov/ca/cwds/cares/services/ReporterServiceImplTest.java
Integration
1. CICS service call was tuned. Minor changes to request and url.
2. Business Rule name was fixed.
3. Created Reporter Id was added to the response.
https://osi-cwds.atlassian.net/browse/REP-3
> REP-3 Fix CICS reporter POST call

- cares-bre/cares-bre-rest-api/src/test/resources/fixtures/rules/ReporterBusinessRulesRequest.json
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-R-00846.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-R-00849.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-confidential-wavier-ind.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-drms-mandated-reporter-feedback.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-employer-name.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-feedback-required-ind.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-fklaw-enft.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-fkreferl-t.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-mandated-reporter-ind.drl
- cares-cics/cares-cics-interfaces/src/test/resources/gov/ca/cwds/cics/model/ReporterDataBuilder.java
Drools file for ReporterBusinessRules required modifications so that class property names matched the ReporterData class.
https://osi-cwds.atlassian.net/browse/REP-52
> adjust drools files to ReporterData class

- build.gradle
Increase the build version to match the current sprint
no issue
> Increase build version

- cares/cares-rest-api/src/main/java/gov/ca/cwds/cares/rest/controller/ReporterController.java
- cares/cares-rest-api/src/test/java/gov/ca/cwds/cares/rest/controller/ReporterControllerTest.java
Response status code was changed to 201
https://osi-cwds.atlassian.net/browse/REP-3
> REP-3 Tuning reporter response

- cares-bre/cares-bre-services/build.gradle
- cares-bre/cares-bre-services/src/main/java/gov/ca/cwds/bre/services/rules/DroolsBusinessRuleBase.java
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-confidential-wavier-ind.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-employer-name.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-feedback-required-ind.drl
- cares-bre/cares-bre-services/src/main/resources/rules/drools/ReporterBusinessRules/reporter-di-mandated-reporter-ind.drl
- cares-bre/cares-bre-services/src/test/java/gov/ca/cwds/bre/services/rules/drools/DroolsBusinessRulesTestBase.java
- cares-bre/cares-bre-services/src/test/java/gov/ca/cwds/bre/services/rules/drools/ReporterBusinessRulesTest.java
BRE service layer unit tests for reporter drools rules
> BRE service layer unit tests for reporter drools rules

- cares-bre/cares-bre-services/src/test/java/gov/ca/cwds/bre/services/rules/drools/DroolsBusinessRulesTestBase.java
Fixed drools test parent class to use generic object
> Fixed drools test parent class to use generic object

- cares-bre/cares-bre-rest-api/src/test/java/gov/ca/cwds/bre/rest/controller/BreRestControllerTest.java
Unit test for BreRestController.
> Unit test for BreRestController

- cares-bre/cares-bre-functional-tests/.gitignore
- cares-bre/cares-bre-functional-tests/build.gradle
- cares-bre/cares-bre-functional-tests/src/main/java/gov/ca/cwds/bre/rest/ReporterBusinessRulesTest.java
- cares-bre/cares-bre-functional-tests/src/main/java/gov/ca/cwds/bre/rest/RestFunctionalTestBase.java
- cares-bre/cares-bre-functional-tests/src/main/resources/rest-functional-test.properties
- settings.gradle
Added happy path BRE rest functional tests
> Added happy path BRE rest functional tests

- cares-ui/src/reporter/models/searchModel.js
- cares-ui/src/reporter/models/searchResultsModel.js
- cares-ui/test/reporter/models/searchModel.test.js
- cares-ui/test/reporter/models/searchResultsModel.test.js
error handling for BRE API requests
[REP-96](https://osi-cwds.atlassian.net/browse/REP-3)
[REP-96](https://osi-cwds.atlassian.net/browse/REP-96)
> REP-96 handle errors from loading json rules

- cares-ui/src/reporter/models/searchModel.js
Fix a problem with search, as it was not sending phone number
[REP-3](https://osi-cwds.atlassian.net/browse/REP-3)
[REP-105](https://osi-cwds.atlassian.net/browse/REP-105)
> REP-105 fix problem with searching on phone number

- cares/cares-rest-api/src/main/java/gov/ca/cwds/cares/rest/controller/ReporterController.java
- cares/cares-rest-api/src/main/java/gov/ca/cwds/cares/rest/controller/exception/CaresRestExceptionHandler.java
- cares/cares-rest-api/src/test/java/gov/ca/cwds/cares/rest/controller/exception/CaresRestExceptionHandlerTest.java
In case of BRE or CICS error responses Cares API will send to to client detailed response with status code 400.
https://osi-cwds.atlassian.net/browse/REP-106
> REP-106 Tune response

- cares-ui/src/reporter/models/searchResultsModel.js
- cares-ui/test/reporter/models/searchResultsModel.test.js
When we are not creating reporters, validation messages should not be shown for creation.
[REP-107](https://osi-cwds.atlassian.net/browse/REP-107)
[REP-3](https://osi-cwds.atlassian.net/browse/REP-3)
> REP-107 only validate creating reporters if we are creating a reporter

- cares-bre/cares-bre-functional-tests/src/main/java/gov/ca/cwds/bre/rest/ReporterBusinessRulesTest.java
> REP-90 Functional tests for BRE

- cares/cares-functional-tests/src/main/java/gov/ca/cwds/cares/rest/reporter/ReporterTest.java
https://osi-cwds.atlassian.net/browse/REP-3
Add functional tests for reporter
> Add functional Test for reporter

- cares-ui/src/reporter/models/searchResultsModel.js
- cares-ui/test/reporter/models/searchResultsModel.test.js
This updates the search results to display first name, last name, and phone number.
Person ID is forthcoming after API updates
[REP-79](https://osi-cwds.atlassian.net/browse/REP-79)
[REP-118](https://osi-cwds.atlassian.net/browse/REP-118)
> REP-118 Expand the search results to include more data

- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/PersonCrossReferenceEntity.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/PersonCrossReferencePK.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/PersonEntity.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/XrefCode.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/repository/PersonCrossReferenceRepository.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/repository/PersonRepository.java
Persistence layer for Person mode has been added
https://osi-cwds.atlassian.net/browse/REP-115
> REP-115 Add persistence layer for Person model

- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/ReporterEntity.java
After analysis I found that everything that needed in this task it's to add new fields to persistence entity. 
https://osi-cwds.atlassian.net/browse/REP-156
> REP-156 Update persistence layer for reporter update

- cares-iir/cares-iir-interfaces/src/main/java/gov/ca/cwds/cares/interfaces/api/ReporterService.java
- cares-iir/cares-iir-interfaces/src/main/java/gov/ca/cwds/cares/interfaces/model/people/Reporter.java
- cares-iir/cares-iir-rest-api/src/main/java/gov/ca/cwds/cares/rest/controller/ReporterController.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/ReporterServiceImpl.java
Stub GET /reporters end point
https://osi-cwds.atlassian.net/browse/REP-151
> Stub GET /reporters end point

- cares-ui/src/reporter/models/baseModel.js
There is a number displayed next to each field. lets get rid of them.
[REP-81](https://osi-cwds.atlassian.net/browse/REP-81)
> Remove the numbers near each field on forms

- cares-iir/cares-iir-interfaces/src/main/java/gov/ca/cwds/cares/interfaces/model/search/hit/PersonSearchHit.java
- cares-iir/cares-iir-interfaces/src/main/java/gov/ca/cwds/cares/interfaces/model/search/hit/SearchHit.java
- cares-iir/cares-iir-interfaces/src/test/java/gov/ca/cwds/cares/interfaces/model/search/SearchResultsTest.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/ReporterEntity.java
- cares-iir/cares-iir-rest-api/src/test/java/gov/ca/cwds/cares/rest/controller/SearchControllerTest.java
Added expanded identifier to person search hit
https://osi-cwds.atlassian.net/browse/REP-113
> Added expanded identifier to person search hit

- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/PersonCrossReferenceEntity.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/PersonCrossReferencePK.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/ReporterEntity.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/repository/PersonCrossReferenceRepository.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/repository/ReporterRepository.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/mapping/search/PersonSearchHitMapper.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/search/jdbc/JdbcSearchService.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/search/jdbc/JdbcSearchServiceTest.java
Fixed persistence layer to lazy load person cross reference with reporter entity. 
Added person id to search results.
https://osi-cwds.atlassian.net/browse/REP-113
> Fixed persistence layer and added person id to search results

- cares-iir/cares-iir-rest-api/docker-compose-cares-iir-rest-api.yml
> Changed RACF pwd

- cares-iir/cares-iir-functional-tests/src/main/java/gov/ca/cwds/cares/rest/search/ReporterSearchTest.java
Expanded id check was added to functional tests
https://osi-cwds.atlassian.net/browse/REP-117
> REP-117 Include expanded id into functional tests

- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/ReporterServiceImpl.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/ReporterServiceImplTest.java
Added proper last updated timestamp to reporter
https://osi-cwds.atlassian.net/browse/REP-155
>  Added proper last updated timestamp to reporter

- cares-iir/cares-iir-rest-api/src/main/resources/application.yml
> Updated z/OS connect host

- cares-cics/cares-cics-rest-client/src/main/java/gov/ca/cwds/cics/CicsRestApiHelper.java
Added some more logging context for z/OS connect errors
> Added some more logging context for z/OS connect errors

- cares-ui/src/reporter/models/reporterModel.js
- cares-ui/test/reporter/models/reporterModel.test.js
Add a bunch of fields to API request when creating a reporter:
* employer name
* title
* address
* city
* zip code
* state
[REP-81](https://osi-cwds.atlassian.net/browse/REP-81)
[REP-205](https://osi-cwds.atlassian.net/browse/REP-205)
> REP-205 Add a bunch of fields when creating a reporter

- cares-common/src/main/java/gov/ca/cwds/cares/common/exception/DataIntegrityException.java
- cares-iir/cares-iir-rest-api/src/main/java/gov/ca/cwds/cares/rest/controller/exception/CaresRestExceptionHandler.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/ReporterServiceImpl.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/mapping/ReporterMapper.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/ReporterServiceImplTest.java
UI id translation is added. Unit test for reporter update is under work for other story and will be added in scope of that story
https://osi-cwds.atlassian.net/browse/REP-207
> REP-207 Add UI id translation

- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/ReporterServiceImplTest.java
Add unit tests
https://osi-cwds.atlassian.net/browse/REP-155
> add unit tests

- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/PersonCrossReferencePK.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/mapping/ReporterMapper.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/ReporterServiceImplTest.java
Mapping of reporter address was added
https://osi-cwds.atlassian.net/browse/REP-207
> REP-213 Add mapping of reporter address

- cares-ui/src/reporter/Reporter.jsx
- cares-ui/src/reporter/jsonForms/search.json
- cares-ui/src/reporter/jsonForms/searchResults.json
- cares-ui/src/reporter/models/reporterModel.js
- cares-ui/src/reporter/models/searchResultsModel.js
- cares-ui/src/reporter/selectors/index.js
- cares-ui/src/routes.js
- cares-ui/test/reporter/models/reporterModel.test.js
to be able to update a reporter or create them depending on the user selection on the search results screen
We should use the store to store the reporter, but that is not necessary for functionality right now.
[REP-81](https://osi-cwds.atlassian.net/browse/REP-81)
[REP-205](https://osi-cwds.atlassian.net/browse/REP-205)
> REP 205 use create and update endpoints

- cares-cics/cares-cics-rest-client/src/main/java/gov/ca/cwds/cics/restclient/CicsReporterRestApiClient.java
Integrate zOS connect Reporter update
https://osi-cwds.atlassian.net/browse/REP-214
> REP-214 Change method to PUT when calling zOS connect reporter update

- cares-ui/src/reporter/models/reporterModel.js
- cares-ui/test/reporter/models/reporterModel.test.js
Add a cancel button to the reporter template that brings the user back to search if they do not want to continue
[REP-81](https://osi-cwds.atlassian.net/browse/REP-81)
[REP-212](https://osi-cwds.atlassian.net/browse/REP-212)
> REP-212 Add a cancel button that takes the user back to search

- cares-ui/src/reporter/models/reporterModel.js
- cares-ui/src/reporter/models/searchResultsModel.js
- cares-ui/test/reporter/models/reporterModel.test.js
When creating or updating a reporter send the state code
[rep-81](https://osi-cwds.atlassian.net/browse/REP-81)
[rep-209](https://osi-cwds.atlassian.net/browse/REP-209)
[rep-210](https://osi-cwds.atlassian.net/browse/REP-210)
> REP-209 add the state code to payload when updating or creating

- cares-iir/cares-iir-functional-tests/src/main/java/gov/ca/cwds/cares/rest/reporter/ReporterTest.java
- cares-iir/cares-iir-functional-tests/src/main/java/gov/ca/cwds/cares/rest/search/ReporterSearchTest.java
> REP-81 created functional tests for saving and updating reporter

- cares-iir/cares-iir-rest-api/src/test/java/gov/ca/cwds/cares/rest/controller/ReporterControllerTest.java
- cares-iir/cares-iir-rest-api/src/test/java/gov/ca/cwds/cares/rest/controller/exception/CaresRestExceptionHandlerTest.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/ReporterServiceImpl.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/ReporterServiceImplTest.java
Unit test were added. Filtering for reporter references was applied. Data integrity check was added
https://osi-cwds.atlassian.net/browse/REP-82
> REP-82 Add unit tests. Filter reporter cross references

- cares-cics/cares-cics-rest-client/build.gradle
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/mapping/AddressMapperTest.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/mapping/ClientAddressMapperTest.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/mapping/ClientMapperTest.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/mapping/ReferralMapperTest.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/mapping/ReporterMapperTest.java
> REP-82 add unit tests for mappers

- cares-iir/cares-iir-interfaces/src/main/java/gov/ca/cwds/cares/interfaces/model/people/Reporter.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/BusinessRulesExecutorImpl.java
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/ReporterServiceImpl.java
Cares IIR service layer issues that are related to current POC were fixed
https://osi-cwds.atlassian.net/browse/REP-82
> Rep 82 sonar fix

- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/mapping/SystemCodeMapperTest.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/mapping/SystemMetaMapperTest.java
> REP-223 add rest of mapper unit tests

- cares-iir/cares-iir-rest-api/docker-compose-cares-iir-rest-api.yml
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/services/mapping/ReporterMapperTest.java
Testing of reporter title and dob updates
https://osi-cwds.atlassian.net/browse/REP-216
https://osi-cwds.atlassian.net/browse/REP-240
>  Testing of reporter title and dob updates

- cares-cics/cares-cics-interfaces/build.gradle
- cares-cics/cares-cics-interfaces/src/test/java/gov/ca/cwds/cics/binding/GeoLocationSerializerTest.java
- cares-common/src/test/java/gov/ca/cwds/cares/common/binding/IdentifierSerializerTest.java
- cares-common/src/test/java/gov/ca/cwds/cares/common/binding/SnakeUpperCaseStrategyTest.java
- cares-common/src/test/java/gov/ca/cwds/cares/common/binding/TrimmingSerializerTest.java
https://osi-cwds.atlassian.net/browse/REP-223
add unit tests for serializers
> REP-223 add unit tests for serializers

- build.gradle
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/SystemCodeEntity.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/repository/SystemCodeRepository.java
- cares-iir/cares-iir-rest-api/docker-compose-cares-iir-rest-api.yml
- cares-iir/cares-iir-services/src/main/java/gov/ca/cwds/cares/services/SystemCodeServiceImpl.java
>  System code sort order

- cares-ui/src/reporter/models/searchResultsModel.js
- Display birthdate on reporter create/update, received from api response
> Display birthdate received from api response

- cares-iir/cares-iir-interfaces/src/main/java/gov/ca/cwds/cares/interfaces/model/Address.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/TrimmingStringType.java
- cares-iir/cares-iir-persistence/src/main/java/gov/ca/cwds/cares/persistence/entity/package-info.java
- cares-iir/cares-iir-services/src/test/java/gov/ca/cwds/cares/persistence/entity/TrimmingStringTypeTest.java
Custom Type for transforming entities values has been added. Every string value will be trimmed if entity is in entities java package
https://osi-cwds.atlassian.net/browse/REP-254
> Rep 254 trim string values on loading from db

- cares-ui/engine/src/customOperators.js
This fixes a problem with phone number validation not displaying when phone number is blank.
[REP-262](https://osi-cwds.atlassian.net/browse/REP-262)
> REP-262 fix phone number validation

- cares-ui/src/reporter/models/searchResultsModel.js
search results were not being cleared when leaving the search results page
[REP-263](https://osi-cwds.atlassian.net/browse/REP-263)
> REP-263 clear search results before leaving the search results page

- cares-ui/src/reporter/jsonForms/search.json
- cares-ui/src/reporter/models/searchModel.js
get the system codes from the API and sort them by other_code
[rep-241](https://osi-cwds.atlassian.net/browse/REP-241)
> rep-241 load the reporter types from the api

- cares-iir/cares-iir-functional-tests/src/main/java/gov/ca/cwds/cares/rest/systemcode/SystemCodesTest.java
System codes functional test for rest end point
https://osi-cwds.atlassian.net/browse/REP-249
> System codes functional test for rest end point
